# Generated by Django 6.0 on 2026-03-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_category_hsncode_order_cgst_amount_order_grand_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
