# Generated by Django 6.0 on 2026-03-24 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_userprofile_gst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsncode',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hsn_codes', to='marketplace.category'),
        ),
    ]
