# Generated by Django 6.0 on 2026-04-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_hsncode_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Business Profile',
                'verbose_name_plural': 'Business Profiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('marketplace.userprofile',),
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Farmer Profile',
                'verbose_name_plural': 'Farmer Profiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('marketplace.userprofile',),
        ),
    ]
